import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, MessageCircle } from "lucide-react";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { contact } from "@/data/content";

export const metadata: Metadata = { title: "Contato", description: "Entre em contato com a Southsea Investments para uma análise estratégica inicial.", alternates: { canonical: "/contato" } };
export default function Contato() {
  return <div className="bg-background pb-20 pt-32 lg:pb-24"><div className="container mx-auto px-5 md:px-10"><Breadcrumbs items={[{ label: "Contato" }]} /><div className="grid gap-12 lg:grid-cols-[1.1fr_0.9fr]"><div><p className="eyebrow">Contato</p><h1 className="section-title">Comece pelo contexto da sua operação.</h1><p className="section-copy mt-5 max-w-2xl">Para que a conversa seja produtiva, a Southsea inicia o contato pela análise das informações essenciais sobre a empresa, objetivo, prazo e estrutura disponível.</p><Link href="/analise-estrategica" className="button-primary mt-8 gap-2">Solicitar análise estratégica <ArrowRight size={17} /></Link></div><div className="border border-white/10 bg-[#101010] p-7"><p className="eyebrow">Canais</p><div className="space-y-6">{contact.email && <a href={`mailto:${contact.email}`} className="flex gap-4 text-foreground/70 transition-colors hover:text-primary"><MessageCircle className="shrink-0 text-primary" size={20} /><span><span className="block text-xs uppercase tracking-[0.14em] text-foreground/40">E-mail</span><span className="mt-1 block">{contact.email}</span></span></a>}<a href={contact.whatsappHref} target="_blank" rel="noreferrer" className="flex gap-4 text-foreground/70 transition-colors hover:text-primary"><MessageCircle className="shrink-0 text-primary" size={20} /><span><span className="block text-xs uppercase tracking-[0.14em] text-foreground/40">WhatsApp</span><span className="mt-1 block">{contact.whatsapp}</span></span></a></div><p className="mt-8 border-t border-white/10 pt-6 text-xs leading-5 text-foreground/40">O canal de contato é o WhatsApp indicado acima, sujeito à validação institucional antes da publicação final.</p></div></div></div></div>;
}