"use client";

import { motion } from "framer-motion";
import { ArrowRight, ArrowUpRight, Building2, CheckCircle2, FileCheck2, Landmark, LineChart, Scale, ShieldCheck } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { Reveal } from "@/components/Reveal";
import { SolutionsCarousel } from "@/components/SolutionsCarousel";
import { operatingModel } from "@/data/content";

const areas = ["Expansão empresarial", "Crédito estruturado", "Reestruturação de passivos", "BNDES e crédito rural", "Mercado de capitais", "Operações internacionais", "Estruturação societária", "Patrimônio e governança"];
const moments = [
  ["Crescimento com estrutura", "Quando a estratégia de expansão precisa caminhar com uma arquitetura de capital e execução compatível."],
  ["Captação com critério", "Quando a companhia avalia fontes de recursos, garantias e prazos para um movimento relevante."],
  ["Reorganização financeira", "Quando obrigações, vencimentos e caixa exigem uma leitura coordenada antes da decisão."],
  ["Operações complexas", "Quando a iniciativa demanda articulação entre finanças, jurídico, governança e especialistas."],
];

export function HomeClient() {
  return (
    <div className="overflow-hidden">
      <section className="relative isolate overflow-hidden bg-[#050505] pb-16 pt-32 lg:pb-24 lg:pt-40">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_88%_12%,rgba(194,142,70,0.14),transparent_27%),radial-gradient(circle_at_4%_80%,rgba(255,255,255,0.035),transparent_38%)]" />
        <div className="container mx-auto grid items-center gap-12 px-5 md:px-10 lg:grid-cols-[1.1fr_0.9fr] lg:gap-16">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.58, ease: [0.22, 1, 0.36, 1] }} className="max-w-3xl">
            <p className="eyebrow">Corporate Advisory & Consulting</p>
            <h1 className="font-serif text-4xl leading-[1.02] text-foreground sm:text-5xl lg:text-7xl">Estruturação financeira para empresas em expansão, reestruturação ou captação de capital.</h1>
            <p className="mt-7 max-w-2xl text-lg leading-8 text-foreground/70 sm:text-xl">A Southsea atua ao lado de empresários, conselhos e diretorias na análise, modelagem e execução de operações financeiras complexas.</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/analise-estrategica" className="button-primary gap-2">Solicitar análise estratégica <ArrowUpRight size={17} /></Link><Link href="/solucoes" className="button-secondary gap-2">Conhecer soluções <ArrowRight size={17} /></Link></div>
            <p className="mt-7 text-xs uppercase tracking-[0.16em] text-foreground/40">Atuação estratégica · Processo confidencial · Critérios de enquadramento</p>
          </motion.div>
          <motion.div initial={{ opacity: 0, scale: 0.97 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.7, delay: 0.1 }} className="relative mx-auto w-full max-w-md lg:max-w-none"><motion.div animate={{ y: [0, -7, 0] }} transition={{ duration: 8, repeat: Infinity, ease: "easeInOut" }}><div className="absolute -inset-4 border border-primary/30" /><div className="relative aspect-[4/5] overflow-hidden border border-white/10 bg-[#111111]"><Image src="/images/7G2A2370.jpg.jpeg" alt="Munaretto, advisor da Southsea Investments" fill priority sizes="(max-width: 1024px) 448px, 42vw" className="object-cover object-top grayscale-[20%] transition-all duration-700 hover:scale-[1.025] hover:grayscale-0" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#050505] via-[#050505]/20 to-transparent p-6 pt-24"><p className="text-xs font-medium uppercase tracking-[0.17em] text-primary">Southsea Investments</p></div><motion.div className="pointer-events-none absolute inset-y-0 -left-1/3 w-1/4 skew-x-[-18deg] bg-gradient-to-r from-transparent via-white/10 to-transparent" animate={{ x: ["0%", "650%"] }} transition={{ duration: 7, repeat: Infinity, repeatDelay: 4, ease: "easeInOut" }} /></div></motion.div></motion.div>
        </div>
      </section>

      <section aria-label="Áreas de atuação" className="group overflow-hidden border-y border-white/10 bg-[#030303] py-6">
        <div className="marquee-mask">
          <div className="marquee-track group-hover:[animation-play-state:paused]">
            {[false, true].map((isDuplicate, copyIndex) => (
              <div key={copyIndex} className="marquee-segment" aria-hidden={isDuplicate || undefined}>
                {areas.map((area) => <span key={`${copyIndex}-${area}`} className="inline-flex items-center gap-7 whitespace-nowrap text-xs font-medium uppercase tracking-[0.15em] text-foreground/60"><span className="h-1 w-1 rounded-full bg-primary/70" />{area}</span>)}
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="bg-background py-20 lg:py-24"><div className="container mx-auto px-5 md:px-10"><Reveal className="max-w-2xl"><p className="eyebrow">Quando a Southsea entra</p><h2 className="section-title">Decisões de capital pedem contexto, método e coordenação.</h2><p className="section-copy mt-5">A atuação começa quando a empresa precisa transformar uma decisão relevante em uma operação financeiramente viável e executável.</p></Reveal><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{moments.map(([title, text], index) => <Reveal key={title} delay={index * 0.06} className="border border-white/10 bg-[#101010] p-6"><FileCheck2 className="mb-6 text-primary" size={22} /><h3 className="font-serif text-2xl text-foreground">{title}</h3><p className="mt-3 text-sm leading-6 text-foreground/60">{text}</p></Reveal>)}</div></div></section>

      <section className="relative overflow-hidden border-y border-white/10 bg-[#030303] py-20 lg:py-24"><div className="pointer-events-none absolute left-1/2 top-0 h-72 w-[55rem] -translate-x-1/2 bg-[radial-gradient(ellipse_at_top,rgba(194,142,70,0.09),transparent_68%)]" /><div className="container relative mx-auto px-5 md:px-10"><Reveal className="max-w-4xl"><p className="eyebrow">Soluções</p><h2 className="section-title">Estruturas desenhadas a partir da operação.</h2></Reveal><SolutionsCarousel /></div></section>

      <section className="bg-background py-20 lg:py-24"><div className="container mx-auto px-5 md:px-10"><Reveal className="max-w-2xl"><p className="eyebrow">Modelo de atuação</p><h2 className="section-title">Do enquadramento à execução acompanhada.</h2><p className="section-copy mt-5">A sequência é adaptada ao estágio e à natureza de cada operação, preservando rigor técnico e visibilidade para a decisão.</p></Reveal><div className="mt-12 grid gap-px overflow-hidden border border-white/10 bg-white/10 md:grid-cols-5">{operatingModel.map((step, index) => <Reveal key={step.number} delay={index * 0.05} className="bg-background p-6"><p className="font-serif text-3xl text-primary/80">{step.number}</p><h3 className="mt-9 font-serif text-xl text-foreground">{step.title}</h3><p className="mt-3 text-sm leading-6 text-foreground/60">{step.text}</p></Reveal>)}</div><Link href="/como-atuamos" className="mt-8 inline-flex items-center gap-2 text-sm text-primary hover:text-primary-light">Entender como atuamos <ArrowRight size={16} /></Link></div></section>

      <section className="border-y border-white/10 bg-[#101010] py-20 lg:py-24"><div className="container mx-auto grid gap-10 px-5 md:px-10 lg:grid-cols-[0.75fr_1.25fr] lg:gap-20"><Reveal><p className="eyebrow">Cases</p><h2 className="section-title">Confidencialidade é parte da estrutura.</h2><p className="section-copy mt-5">A Southsea não publica nomes, cifras, resultados ou detalhes operacionais sem autorização formal das partes envolvidas.</p><Link href="/cases" className="mt-7 inline-flex items-center gap-2 text-sm text-primary hover:text-primary-light">Nossa política de cases <ArrowRight size={16} /></Link></Reveal><Reveal className="border border-white/10 bg-[#080808] p-6 sm:p-8"><div className="grid gap-7 sm:grid-cols-2">{[["Contexto", "Apresentado somente quando houver autorização e preservação de informações sensíveis."], ["Necessidade", "Definida a partir do diagnóstico específico de cada companhia."], ["Estrutura desenhada", "Descrita conforme escopo autorizado e obrigações de confidencialidade."], ["Resultado autorizado", "Nenhum resultado é divulgado sem validação e permissão expressa."]].map(([title, text]) => <div key={title}><p className="eyebrow !mb-2">{title}</p><p className="text-sm leading-6 text-foreground/70">{text}</p></div>)}</div></Reveal></div></section>

      <section className="bg-background py-20 lg:py-24"><div className="container mx-auto grid items-center gap-12 px-5 md:px-10 lg:grid-cols-[0.78fr_1.22fr] lg:gap-20"><Reveal className="group relative mx-auto aspect-[4/5] w-full max-w-sm border border-primary/30"><div className="absolute -bottom-3 -right-3 h-full w-full border border-primary/20 transition-transform duration-500 group-hover:translate-x-1.5 group-hover:translate-y-1.5" /><Image src="/images/7G2A2376.jpg.jpeg" alt="Munaretto" fill sizes="(max-width: 1024px) 384px, 30vw" className="object-cover grayscale-[25%] transition-all duration-700 group-hover:scale-[1.025] group-hover:grayscale-0" /></Reveal><Reveal><p className="eyebrow">Munaretto</p><h2 className="section-title">Advisor para decisões financeiras que exigem visão de conjunto.</h2><p className="section-copy mt-5">Munaretto atua na Southsea Investments como advisor, apoiando empresários, conselhos e diretorias na leitura estratégica de operações financeiras complexas.</p><p className="section-copy mt-4">A prática combina visão de capital, organização de premissas, diálogo multidisciplinar e relacionamento corporativo no Brasil e em operações internacionais.</p><Link href="/sobre" className="mt-8 inline-flex items-center gap-2 text-sm text-primary hover:text-primary-light">Conhecer a Southsea <ArrowRight size={16} /></Link></Reveal></div></section>

      <section className="border-y border-white/10 bg-[#030303] py-20 lg:py-24"><div className="container mx-auto px-5 md:px-10"><Reveal className="max-w-2xl"><p className="eyebrow">Capacidade multidisciplinar</p><h2 className="section-title">Uma operação raramente é apenas financeira.</h2></Reveal><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[{ icon: LineChart, title: "Estratégia financeira", text: "Premissas, cenários, fontes de capital e capacidade de execução." }, { icon: Scale, title: "Coordenação jurídica", text: "Integração com assessores para estrutura, contratos e aspectos societários." }, { icon: Building2, title: "Visão corporativa", text: "Leitura do negócio, governança, operação e interlocutores envolvidos." }, { icon: Landmark, title: "Contexto internacional", text: "Apoio estratégico para estruturas que envolvam diferentes mercados e contrapartes." }].map((item, index) => <Reveal key={item.title} delay={index * 0.06} className="border border-white/10 bg-[#080808] p-6"><item.icon className="text-primary" size={23} /><h3 className="mt-8 font-serif text-2xl text-foreground">{item.title}</h3><p className="mt-3 text-sm leading-6 text-foreground/60">{item.text}</p></Reveal>)}</div></div></section>

      <section className="bg-background py-20 lg:py-24"><div className="container mx-auto px-5 md:px-10"><Reveal className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div className="max-w-2xl"><p className="eyebrow">Indicadores validados</p><h2 className="section-title">Transparência antes de qualquer métrica.</h2><p className="section-copy mt-5">Cifras, prazos, localizações, quantidade de empresas e resultados institucionais são divulgados somente após validação com o cliente e, quando aplicável, autorização das partes.</p></div><ShieldCheck className="text-primary" size={34} /></Reveal><div className="mt-10 grid gap-4 md:grid-cols-3">{["Operações e volumes", "Prazos e marcos", "Resultados e referências"].map((item) => <Reveal key={item} className="border border-white/10 p-6"><p className="font-serif text-2xl text-foreground">{item}</p><p className="mt-3 text-sm leading-6 text-foreground/60">Informações institucionais em processo de validação antes de eventual publicação.</p></Reveal>)}</div></div></section>

      <section className="border-y border-white/10 bg-[#101010] py-20 lg:py-24"><div className="container mx-auto grid gap-10 px-5 md:px-10 lg:grid-cols-2"><Reveal><p className="eyebrow">Governança e conformidade</p><h2 className="section-title">Rigor de processo para decisões sensíveis.</h2><p className="section-copy mt-5">A atuação considera critérios de enquadramento, organização das informações, confidencialidade e a participação dos profissionais habilitados para cada frente.</p></Reveal><Reveal className="grid gap-5 sm:grid-cols-2">{["Confidencialidade e tratamento responsável de informações", "Coordenação com especialistas conforme a natureza da operação", "Decisões apoiadas por premissas e documentação organizada", "Acompanhamento de marcos e obrigações definidos no escopo"].map((item) => <div key={item} className="flex gap-3 border border-white/10 bg-[#080808] p-5 text-sm leading-6 text-foreground/70"><CheckCircle2 className="mt-0.5 shrink-0 text-primary" size={17} />{item}</div>)}</Reveal></div></section>

      <section className="bg-background py-20 lg:py-24"><div className="container mx-auto px-5 md:px-10"><Reveal className="border border-primary/30 bg-[linear-gradient(115deg,#111111,#080808_52%,#101010)] p-7 sm:p-10"><p className="eyebrow">Educação executiva</p><div className="grid items-end gap-7 lg:grid-cols-[1.25fr_0.75fr]"><div><h2 className="section-title">O Código Financeiro Corporativo</h2><p className="section-copy mt-5">Conteúdo educacional complementar para quem deseja aprofundar conceitos de capital, estrutura financeira e decisões corporativas. A educação executiva tem identidade própria e não substitui uma análise dedicada.</p></div><Link href="/curso" className="button-secondary justify-center gap-2 border-primary/50 text-primary hover:bg-primary hover:text-[#080808]">Conhecer o programa <ArrowRight size={17} /></Link></div></Reveal></div></section>

      <section className="bg-[#030303] py-20 lg:py-24"><div className="container mx-auto px-5 text-center md:px-10"><Reveal className="mx-auto max-w-3xl"><p className="eyebrow">Próximo passo</p><h2 className="section-title">Vamos entender o contexto da sua operação.</h2><p className="section-copy mt-5">Compartilhe as informações iniciais. A análise de enquadramento considera o momento da empresa, o objetivo e os elementos disponíveis para estruturação.</p><Link href="/analise-estrategica" className="button-primary mt-8 gap-2">Solicitar análise estratégica <ArrowUpRight size={17} /></Link></Reveal></div></section>
    </div>
  );
}