import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CircleCheck } from "lucide-react";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { course } from "@/data/content";

export const metadata: Metadata = { title: "O Código Financeiro Corporativo", description: course.description, alternates: { canonical: "/curso" } };
const modules = [
  ["Leitura financeira corporativa", "Princípios para organizar informações e enxergar a estrutura financeira do negócio."],
  ["Capital e garantias", "Conceitos para apoiar a avaliação de fontes de recursos, prazos e garantias."],
  ["Passivos e decisões", "Perspectivas para compreender obrigações e seus efeitos sobre a operação."],
  ["Preparação para diálogo", "Elementos para se preparar para conversas com sócios, gestores, instituições e assessores."],
];
export default function Curso() {
  return <div className="min-h-screen bg-[#0b0b0b] pb-20 pt-32"><div className="absolute inset-x-0 top-0 -z-10 h-[560px] bg-[radial-gradient(circle_at_76%_4%,rgba(194,142,70,0.2),transparent_33%)]" /><div className="container mx-auto px-5 md:px-10"><Breadcrumbs items={[{ label: "O Código Financeiro Corporativo" }]} /><section className="grid gap-12 border-b border-white/10 pb-16 lg:grid-cols-[1.2fr_0.8fr]"><div><p className="eyebrow">Educação executiva · Southsea</p><h1 className="font-serif text-4xl leading-tight text-foreground sm:text-5xl lg:text-6xl">{course.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-foreground/70">Um programa de educação executiva para líderes que desejam ampliar sua compreensão sobre decisões de capital, estrutura financeira e diálogo corporativo.</p><p className="mt-6 max-w-2xl text-sm leading-6 text-foreground/50">Este é um produto educacional independente. Não substitui análise estratégica, assessoria jurídica, contábil ou financeira dedicada.</p></div><aside id="checkout" className="border border-primary/40 bg-[#12100b] p-7 sm:p-9"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Acesso ao programa</p><p className="mt-6 font-serif text-5xl text-foreground">{course.price}</p><p className="mt-3 text-sm leading-6 text-foreground/60">Valor informado no projeto e sujeito à confirmação comercial antes da publicação.</p><Link href="/contato" className="button-primary mt-8 w-full gap-2">Manifestar interesse <ArrowRight size={17} /></Link><p className="mt-4 text-xs leading-5 text-foreground/50">Integração de checkout reservada para configuração futura.</p></aside></section><section className="py-16"><p className="eyebrow">Conteúdo</p><h2 className="section-title max-w-2xl">Uma base de conceitos para conversas mais qualificadas.</h2><div className="mt-10 grid gap-4 md:grid-cols-2">{modules.map(([title, text], index) => <article key={title} className="border border-white/10 bg-[#12100b] p-6"><p className="font-serif text-3xl text-primary">0{index + 1}</p><h3 className="mt-8 font-serif text-2xl text-foreground">{title}</h3><p className="mt-3 text-sm leading-6 text-foreground/70">{text}</p></article>)}</div></section><section className="border-t border-white/10 pt-12"><h2 className="font-serif text-3xl text-foreground">Para quem é</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{["Sócios e empresários que participam de decisões financeiras", "Diretores e líderes que precisam dialogar sobre capital e operação", "Profissionais interessados em ampliar repertório executivo"].map((item) => <p className="flex gap-3 text-sm leading-6 text-foreground/70" key={item}><CircleCheck className="mt-0.5 shrink-0 text-primary" size={17} />{item}</p>)}</div></section></div></div>;
}